# Generated by Django 5.2.14 on 2026-05-23 11:05

import apps.files.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.files.models.upload_to, verbose_name='文件')),
                ('file_url', models.CharField(blank=True, max_length=500, verbose_name='访问 URL')),
                ('file_type', models.CharField(choices=[('avatar', '用户头像'), ('pet', '宠物头像'), ('medical', '就诊记录'), ('ai', 'AI 咨询'), ('product', '商品'), ('service', '服务')], default='pet', max_length=32, verbose_name='文件类型')),
                ('content_type', models.CharField(max_length=100, verbose_name='MIME 类型')),
                ('size', models.PositiveIntegerField(verbose_name='文件大小')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='files_user_idx'), models.Index(fields=['file_type'], name='files_type_idx')],
            },
        ),
    ]
