# Generated by Django 5.2.14 on 2026-05-26 03:42

import apps.shop.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.productcategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='单位')),
                ('spec', models.CharField(blank=True, max_length=128, verbose_name='规格')),
                ('barcode', models.CharField(max_length=64, unique=True, verbose_name='条码')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='进货价')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='零售价')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量')),
                ('shelf_life_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='保质期（月）')),
                ('cover_image', models.CharField(blank=True, max_length=500, verbose_name='商品主图')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '上架'), ('inactive', '下架')], default='active', max_length=20, verbose_name='商品状态')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.shop.models.product_import_upload_to, verbose_name='原始 Excel 文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='总数据行数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='新增成功数量')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='更新数量')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数量')),
                ('image_success_count', models.PositiveIntegerField(default=0, verbose_name='图片成功提取数量')),
                ('image_failed_count', models.PositiveIntegerField(default=0, verbose_name='图片提取失败数量')),
                ('status', models.CharField(choices=[('processing', '处理中'), ('success', '成功'), ('failed', '失败'), ('partial_success', '部分成功')], default='processing', max_length=32, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='整体错误信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='导入人')),
            ],
            options={
                'verbose_name': '商品导入批次',
                'verbose_name_plural': '商品导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(verbose_name='Excel 行号')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='商品名称')),
                ('barcode', models.CharField(blank=True, max_length=64, verbose_name='条码')),
                ('status', models.CharField(choices=[('success', '新增成功'), ('updated', '更新成功'), ('failed', '失败')], max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='shop.productimportbatch', verbose_name='导入批次')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='shop.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品导入明细',
                'verbose_name_plural': '商品导入明细',
                'ordering': ['batch_id', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store_code', models.CharField(default='DEFAULT', max_length=64, verbose_name='直营店序号')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='当前库存')),
                ('last_imported_at', models.DateTimeField(blank=True, null=True, verbose_name='最后导入时间')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='shop.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品库存',
                'verbose_name_plural': '商品库存',
                'ordering': ['product_id', 'store_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='shop_category_parent_name_uniq'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='shop_product_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='shop_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='shop_product_category_idx'),
        ),
        migrations.AddIndex(
            model_name='productimportrow',
            index=models.Index(fields=['batch', 'status'], name='shop_imp_row_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productimportrow',
            index=models.Index(fields=['barcode'], name='shop_imp_row_barcode_idx'),
        ),
        migrations.AddIndex(
            model_name='productinventory',
            index=models.Index(fields=['store_code'], name='shop_inventory_store_idx'),
        ),
        migrations.AddConstraint(
            model_name='productinventory',
            constraint=models.UniqueConstraint(fields=('product', 'store_code'), name='shop_inventory_product_store_uniq'),
        ),
    ]
