# Generated by Django 5.2.14 on 2026-05-23 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=64, verbose_name='宠物名称')),
                ('species', models.CharField(choices=[('cat', '猫'), ('dog', '狗'), ('other', '其他')], default='cat', max_length=20, verbose_name='物种')),
                ('breed', models.CharField(blank=True, max_length=64, verbose_name='品种')),
                ('gender', models.CharField(choices=[('male', '公'), ('female', '母'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('avatar', models.URLField(blank=True, max_length=500, verbose_name='宠物头像')),
                ('color', models.CharField(blank=True, max_length=64, verbose_name='毛色')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='当前体重')),
                ('neutered', models.BooleanField(default=False, verbose_name='是否绝育')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '宠物',
                'verbose_name_plural': '宠物',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('record_type', models.CharField(choices=[('vaccine', '疫苗'), ('deworm', '驱虫'), ('medical', '就诊'), ('allergy', '过敏'), ('other', '其他')], default='other', max_length=32, verbose_name='记录类型')),
                ('title', models.CharField(max_length=128, verbose_name='记录标题')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('next_remind_date', models.DateField(blank=True, null=True, verbose_name='下次提醒日期')),
                ('hospital', models.CharField(blank=True, max_length=128, verbose_name='医院')),
                ('doctor', models.CharField(blank=True, max_length=64, verbose_name='医生')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='pets.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '健康记录',
                'verbose_name_plural': '健康记录',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='体重')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='pets.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '体重记录',
                'verbose_name_plural': '体重记录',
                'ordering': ['record_date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner'], name='pets_pet_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['species'], name='pets_pet_species_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['pet'], name='pets_health_pet_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['record_type'], name='pets_health_type_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['next_remind_date'], name='pets_health_remind_idx'),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['pet'], name='pets_weight_pet_idx'),
        ),
        migrations.AddIndex(
            model_name='weightrecord',
            index=models.Index(fields=['record_date'], name='pets_weight_date_idx'),
        ),
    ]
