# Generated by Django 5.2.14 on 2026-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.CharField(blank=True, max_length=500, verbose_name='宠物头像'),
        ),
    ]
